import type { MetadataRoute } from "next";

/**
 * robots.txt — generated by Next 15 native robots route.
 *
 * Public routes (landing, signup, login, legal) are crawlable. Anything
 * private to the shop (dashboard, billing) or transactional (tap pages,
 * unsubscribe tokens, magic links) is blocked even though most are
 * dynamic and uncrawlable anyway — defence in depth.
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://smarttap.ie";

  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/dashboard/",
          "/onboarding",
          "/api/",
          "/auth/",
          "/t/",
          "/u/",
          "/m/",
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
