import type { MetadataRoute } from "next";

/**
 * sitemap.xml — generated by Next 15 native sitemap route.
 *
 * Lists every public crawlable route. Update when new marketing or
 * legal pages land. Dashboards and transactional pages stay out — they
 * are blocked by robots.txt anyway.
 *
 * `lastModified` is set to build time so each deploy bumps the freshness
 * signal; `changeFrequency` is conservative (monthly) because most
 * landing copy is stable.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://smarttap.ie";
  const now = new Date();

  return [
    {
      url: `${baseUrl}/`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${baseUrl}/signup`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/login`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.4,
    },
    {
      url: `${baseUrl}/privacy`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${baseUrl}/terms`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${baseUrl}/gdpr`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.3,
    },
  ];
}
