import type { Metadata } from "next";
import * as React from "react";

import { Footer } from "./_components/footer";
import { LandingJsonLd } from "./_components/json-ld";
import { TopBanner } from "./_components/top-banner";

/**
 * Landing-only layout. Wraps the public marketing surface with the sticky
 * top banner + footer. The (landing) route group keeps this scoped to the
 * home page — `/dashboard`, `/login`, `/t/[uuid]` etc. still use the root
 * layout and never see this chrome.
 *
 * Metadata extends the root layout's defaults — adds the OG image
 * generated by `app/opengraph-image.tsx` (Phase 6) and locks the page
 * title to the marketing headline rather than the title template.
 */
export const metadata: Metadata = {
  title: "SmartTap — One tap. Reviews go up. Regulars come back.",
  alternates: {
    canonical: "/",
  },
};

export default function LandingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-dvh flex-col bg-electric-bg text-electric-text">
      <LandingJsonLd />
      <TopBanner />
      {/* Skip link for keyboard users — surfaces on :focus only. */}
      <a
        href="#main"
        className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-electric-cyan focus:px-4 focus:py-2 focus:text-electric-bg focus:shadow-lg"
      >
        Skip to content
      </a>
      <main id="main" className="flex-1">
        {children}
      </main>
      <Footer />
    </div>
  );
}
