"""Business rules for NFC tags (S5-W0).

Thin orchestration over db/nfc_tags — the heavy lifting is the schema
layer (which constrains format/color to in-stock values) and the public
tap path (which already refuses inactive tags). This module exists to
keep tenant isolation in one place and to give the router a uniform
NotFound on cross-tenant ids.
"""

from typing import Any

import structlog

from app.db import nfc_tags
from app.errors import NotFoundError
from app.schemas.nfc_tag import NfcTagColor, NfcTagFormat

log = structlog.get_logger(__name__)

Row = dict[str, Any]


def list_for_tenant(tenant_id: str) -> list[Row]:
    return nfc_tags.list_for_tenant(tenant_id)


def get_owned(tenant_id: str, tag_id: str) -> Row:
    """Fetch + assert tenant ownership. Raises NotFoundError on missing OR
    cross-tenant — same anti-enumeration pattern as segment_service."""
    row = nfc_tags.get_by_id(tag_id)
    if row is None or row.get("tenant_id") != tenant_id:
        raise NotFoundError("Tag not found", detail={"tag_id": tag_id})
    return row


def create_tag(
    *,
    tenant_id: str,
    format: NfcTagFormat,
    color: NfcTagColor,
    location_name: str | None,
) -> Row:
    """Create one tag. tag_uuid auto-generated by DB default; never
    accepted from the caller because it's stamped on the physical NFC
    chip and must stay stable."""
    clean_location = location_name.strip() if location_name else None
    if clean_location == "":
        # An all-whitespace input is effectively unset — store NULL so
        # the dashboard's "<format> · <color>" fallback kicks in.
        clean_location = None
    row = nfc_tags.create(
        {
            "tenant_id": tenant_id,
            "format": format,
            "color": color,
            "location_name": clean_location,
            "is_active": True,
        }
    )
    log.info(
        "nfc_tag_created",
        tenant_id=tenant_id,
        tag_id=row["id"],
        tag_uuid=row["tag_uuid"],
    )
    return row


def update_tag(
    *,
    tenant_id: str,
    tag_id: str,
    format: NfcTagFormat | None = None,
    color: NfcTagColor | None = None,
    location_name: str | None = None,
    is_active: bool | None = None,
    location_name_explicitly_set: bool = False,
) -> Row:
    """Partial update. Only sent fields change.

    `location_name_explicitly_set` distinguishes "caller didn't include
    this field" (keep current) from "caller sent null/empty" (clear it).
    Pydantic's `model_fields_set` is the canonical source for that in the
    router, which is why we accept the flag rather than re-derive it here.
    """
    # Ownership check is the side-effect even with nothing to update —
    # gives the router a clean 404 path.
    get_owned(tenant_id, tag_id)

    fields: dict[str, Any] = {}
    if format is not None:
        fields["format"] = format
    if color is not None:
        fields["color"] = color
    if location_name_explicitly_set:
        # Normalise empty/whitespace to NULL so the fallback label kicks
        # in instead of rendering a blank string.
        cleaned = location_name.strip() if location_name else None
        fields["location_name"] = cleaned if cleaned else None
    if is_active is not None:
        fields["is_active"] = is_active

    if not fields:
        return get_owned(tenant_id, tag_id)

    updated = nfc_tags.update(tag_id, fields)
    log.info("nfc_tag_updated", tenant_id=tenant_id, tag_id=tag_id, fields=list(fields))
    return updated
