from typing import Any, cast

from app.services.supabase_client import get_supabase_admin

Row = dict[str, Any]


def list_for_tenant(tenant_id: str) -> list[Row]:
    """All tags for a tenant — both active and inactive, newest first.

    Inactive tags are still listed so the merchant can re-activate or
    rename a tag they took out of service (lost stand, moved location)
    without having to touch SQL."""
    client = get_supabase_admin()
    res = (
        client.table("nfc_tags")
        .select("*")
        .eq("tenant_id", tenant_id)
        .order("created_at", desc=True)
        .execute()
    )
    return cast(list[Row], res.data or [])


def create(fields: dict[str, Any]) -> Row:
    """Insert a new tag. `tag_uuid` is auto-generated by the DB default
    (`gen_random_uuid()`); callers should NOT supply one — that's the
    immutable public id stamped onto the physical NFC tag."""
    client = get_supabase_admin()
    res = client.table("nfc_tags").insert(fields).execute()
    rows = cast(list[Row], res.data or [])
    if not rows:
        raise ValueError("nfc_tag not created")
    return rows[0]


def update(tag_id: str, fields: dict[str, Any]) -> Row:
    client = get_supabase_admin()
    res = client.table("nfc_tags").update(fields).eq("id", tag_id).execute()
    rows = cast(list[Row], res.data or [])
    if not rows:
        raise ValueError(f"nfc_tag {tag_id} not updated")
    return rows[0]


def get_by_tag_uuid(tag_uuid: str) -> Row | None:
    client = get_supabase_admin()
    res = client.table("nfc_tags").select("*").eq("tag_uuid", tag_uuid).limit(1).execute()
    rows = cast(list[Row], res.data or [])
    return rows[0] if rows else None


def get_by_id(tag_id: str) -> Row | None:
    client = get_supabase_admin()
    res = client.table("nfc_tags").select("*").eq("id", tag_id).limit(1).execute()
    rows = cast(list[Row], res.data or [])
    return rows[0] if rows else None


def get_by_ids(tag_ids: list[str]) -> list[Row]:
    """Batch lookup used by the monthly report when resolving the top tag's
    human-friendly label. Returns whatever rows exist; missing ids are
    silently dropped (a deleted tag should not crash a report)."""
    if not tag_ids:
        return []
    client = get_supabase_admin()
    res = (
        client.table("nfc_tags")
        .select("id,format,color,location_name")
        .in_("id", tag_ids)
        .execute()
    )
    return cast(list[Row], res.data or [])
