"""Pydantic models for NFC tags (S5-W0).

Format and color are constrained to the values we actually print and
stock:
    - 4 formats mirror the DB CHECK constraint from migration 001
      (counter_stand / table_tent / wall_plaque / sticker).
    - 10 colors mirror the PLA filament stock listed in CLAUDE.md.
      Limiting the schema to in-stock colors stops a merchant requesting
      a tag in a colour we can't print.

`tag_uuid` is generated by the DB and is what gets written onto the
physical NFC tag — it's the path component of the public URL
`https://smarttap.ie/t/<tag_uuid>`. Immutable after creation.
"""

from typing import Literal

from pydantic import BaseModel, Field

NfcTagFormat = Literal["counter_stand", "table_tent", "wall_plaque", "sticker"]

NfcTagColor = Literal[
    "black",
    "white",
    "grey",
    "navy",
    "purple",
    "red",
    "yellow",
    "stone_age",
    "real_green",
    "forest_green",
]


class NfcTagCreateIn(BaseModel):
    """Payload for `POST /v1/tags`."""

    format: NfcTagFormat
    color: NfcTagColor
    # Optional human label — "Front desk", "Bar", "Reception". When unset
    # the dashboard renders the tag as "<format> · <color>".
    location_name: str | None = Field(default=None, max_length=80)


class NfcTagUpdateIn(BaseModel):
    """Patch a tag. All fields optional — only sent fields change. The
    immutable `tag_uuid` is never patchable."""

    format: NfcTagFormat | None = None
    color: NfcTagColor | None = None
    location_name: str | None = Field(default=None, max_length=80)
    # Soft-delete toggle. tap_service refuses inactive tags, so flipping
    # this is the "delete" path that preserves tap history.
    is_active: bool | None = None


class NfcTagOut(BaseModel):
    id: str
    tenant_id: str
    tag_uuid: str
    tag_number: int | None  # per-tenant sequential label (#1, #2, …)
    format: NfcTagFormat
    color: NfcTagColor
    location_name: str | None
    is_active: bool
    deployed_at: str | None
    created_at: str


class NfcTagListResponse(BaseModel):
    items: list[NfcTagOut]
